version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    env_file: docker/development.env
    links:
      - mongo
    ports:
      - '3000:3000'
    # mount source volume, but
    # don't overwrite `node_modules` or mirror dir from container
    volumes:
      - ${PWD}:/usr/src
      - /usr/src/node_modules
    tty: true

  mongo:
    image: mongo
    tty: false
    # Optionally mount external data directory
    # volumes:
    #   - path-to-your-data-dir:/data/db
